version: 2

project_name: rlmkit

before:
  hooks:
    - go test ./...

builds:
  - id: rlmkit
    main: ./cmd/rlmkit
    binary: rlmkit
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

